
#Mekanism Common Config. This config is not sync'd between server and client.
[common]
	#Displayed energy type in Mekanism GUIs and network reader readings.
	#Allowed Values: JOULES, FORGE_ENERGY, ELECTRICAL_UNITS
	energyType = "FORGE_ENERGY"
	#Displayed temperature unit in Mekanism GUIs and network reader readings.
	#Allowed Values: KELVIN, CELSIUS, RANKINE, FAHRENHEIT, AMBIENT
	temperatureUnit = "KELVIN"

