
[general]
	unsupportedDeveloperTools = false
	#Enables the ability of the Matter Cannon to break blocks.
	matterCannonBlockDamage = true
	#Enables the ability of Tiny TNT to break blocks.
	tinyTntBlockDamage = true
	#Server operators are not restricted by ME security terminal settings.
	serverOpsIgnoreSecurity = true
	#Changes the channel capacity that cables provide in AE2.
	#Allowed Values: INFINITE, DEFAULT, X2, X3, X4
	channels = "DEFAULT"
	#The number of pathfinding steps that are taken per tick and per grid that is booting. Lower numbers will mean booting takes longer, but less work is done per tick.
	#Range: 1 ~ 1024
	pathfindingStepsPerTick = 4

[automation]
	#TODO
	formationPlaneEntityLimit = 128

[facades]
	#Unsupported: Allows whitelisting block entities as facades. Could work, have render issues, or corrupt your world. USE AT YOUR OWN RISK.
	allowBlockEntities = false

[craftingCPU]
	craftingCalculationTimePerTick = 5

[crafting]
	#Enable the in-world crafting of singularities.
	inWorldSingularity = true
	#Enable the in-world crafting of fluix crystals.
	inWorldFluix = true
	#Enable the in-world crafting of pure crystals.
	inWorldCrystalGrowth = true
	#Enable shift-clicking with the crafting units in hand to disassemble them.
	disassemblyCrafting = true

[spatialio]
	spatialPowerMultiplier = 1250.0
	spatialPowerExponent = 1.35

[logging]
	securityAuditLog = false
	blockUpdateLog = false
	packetLog = false
	craftingLog = false
	debugLog = false
	#Enable stack trace logging for the chunk loading debug command
	chunkLoggerTrace = false
	gridLog = false

[battery]
	#The chargers charging rate factor, which is applied to the charged items charge rate. 2 means it charges everything twice as fast. 0.5 half as fast.
	#Range: 0.1 ~ 10.0
	chargerChargeRate = 1.0
	wirelessTerminal = 1600000
	chargedStaff = 8000
	entropyManipulator = 200000
	portableCell = 20000
	colorApplicator = 20000
	matterCannon = 200000

[worldGen]
	spawnPressesInMeteorites = true
	generateQuartzOre = true
	quartzOresPerCluster = 7
	quartzOresClusterAmount = 20
	quartzOresBiomeBlacklist = []

[wireless]
	wirelessBaseCost = 8.0
	wirelessCostMultiplier = 1.0
	wirelessBaseRange = 16.0
	wirelessBoosterRangeMultiplier = 1.0
	wirelessBoosterExp = 1.5
	wirelessHighWirelessCount = 64.0
	wirelessTerminalDrainMultiplier = 1.0

[PortableCells]
	#Allow disassembly of portable cells into the recipe ingredients using shift+right-click
	allowDisassembly = true

	[PortableCells.PowerRatios]
		ForgeEnergy = 0.5
		#Range: 0.01 ~ 1.7976931348623157E308
		UsageMultiplier = 1.0

	[PortableCells.Condenser]
		MatterBalls = 256
		Singularity = 256000

	# Min / Max Tickrates for dynamic ticking, most of these components also use sleeping, to prevent constant ticking, adjust with care, non standard rates are not supported or tested.
	[PortableCells.tickRates]
		InterfaceMin = 5
		InterfaceMax = 120
		ImportBusMin = 5
		ImportBusMax = 40
		ExportBusMin = 5
		ExportBusMax = 60
		AnnihilationPlaneMin = 2
		AnnihilationPlaneMax = 120
		METunnelMin = 5
		METunnelMax = 20
		InscriberMin = 1
		InscriberMax = 1
		ChargerMin = 10
		ChargerMax = 10
		IOPortMin = 1
		IOPortMax = 5
		VibrationChamberMin = 10
		VibrationChamberMax = 40
		StorageBusMin = 5
		StorageBusMax = 60
		ItemTunnelMin = 5
		ItemTunnelMax = 60
		LightTunnelMin = 5
		LightTunnelMax = 60

	#Settings for in-world growth of crystals.
	[PortableCells.inWorldCrystalGrowth]
		#A fluid tag that identifies fluids that improve crystal growth speed. Does not affect growth with water/lava.
		improvedFluidTag = ""
		#The speed multiplier to use when the crystals are submerged in the improved fluid.
		#Range: 1.0 ~ 10.0
		improvedFluidMultiplier = 2.0

