
#Lighting
[lights]
	#If dynamic lights are enabled
	lightsEnabled = false
	#How bright the touch light is
	#Range: 0 ~ 15
	touchLightLuminance = 8
	#How long the touch light lasts in ticks
	#Range: 0 ~ 40
	touchLightDuration = 8
	#X offset for the tooltip
	#Range: > -2147483648
	xTooltip = 20
	#Y offset for the tooltip
	#Range: > -2147483648
	yTooltip = 0
	#X offset for the Mana Bar
	#Range: > -2147483648
	xManaBar = 0
	#Y offset for the Mana Bar
	#Range: > -2147483648
	yManaBar = 0
	#Light level an entity should emit when dynamic lights are on
	#Example entry: minecraft:blaze=15
	entity_lights = ["minecraft:blaze=10", "ars_nouveau:orbit=15", "ars_nouveau:linger=15", "ars_nouveau:spell_proj=15", "minecraft:magma_cube=8", "ars_nouveau:flying_item=10", "minecraft:spectral_arrow=8", "ars_nouveau:follow_proj=10"]
	#Light level an item should emit when held when dynamic lights are on
	#Example entry: minecraft:stick=15
	item_lights = ["minecraft:glowstone_dust=8", "minecraft:redstone_torch=10", "minecraft:glowstone=15", "minecraft:blaze_rod=10", "minecraft:torch=14", "minecraft:soul_torch=10"]

