
["Client Options"]
	#Do you want to enable "Cool Dude Mode", enabling easter-egg/meme effects?
	#There are no effects on gameplay, except some text, graphics, and names.
	coolDudeMode = false
	#If JEI is installed, should support be enabled?
	jeiSupport = true
	#Do you want to render custom tooltip frame colors for some specific items?
	#If false, the tooltip will be standard.
	customTooltipColors = true
	#Do you want to render custom tooltip frame textures for some specific items?
	#If false, the tooltip will be standard. This has no effect if customTooltipColors is false.
	customTooltipFrames = true

