
["Machine Options"]
	#If using the Crank without meaning, what chould be the chance it snaps?
	#Value is 1 in X chance to snap, where X is the value in the config.
	#Set to -1 to disable snapping completely.
	crankSnapChance = 100
	#Interact Mode (in the Interactor block) can cause issues with intercompatability with some mods. Do you want this mode enabled?
	#For example, attempting to "interact with" a block with a GUI will cause an exception.
	interactorInteractMode = true
	#Should Interact Mode (in the Interactor block) fail with an exception, what type of logging should be performed?
	#NONE - Interact Mode exceptions are completely silenced.
	#BASIC - The first line of the exception, a simple description, is placed in the console. (If unsure, use this!)
	#COMPLETE - Full stack traces are placed in the console, useful for debugging.
	#Allowed Values: NONE, BASIC, COMPLETE
	interactorInteractDebug = "BASIC"
	#If the Entropy Reactor reaches higher than 98% Entropy, should it explode?
	reactorExplosions = true
	#What is the maximum amount of FE the Tool Charger can place into an item per cycle?
	#The Tool Charger runs one cycle every 2.5 seconds.
	toolChargerChargeRate = 10000
	#What should the FE capacity of the Tool Charger be?
	toolChargerMaxEnergyStorage = 100000

	#What fluids should be valid for use in the Geothermal Generator?
	[["Machine Options".geothermalFluids]]
		fluid = "minecraft:lava"
		value = 115000

	[["Machine Options".geothermalFluids]]
		fluid = "assemblylinemachines:naphtha"
		value = 650000

	#What fluids should be valid for use in the Combustion Generator?
	[["Machine Options".combustionFluids]]
		fluid = "assemblylinemachines:liquid_carbon"
		value = 300000

	[["Machine Options".combustionFluids]]
		fluid = "assemblylinemachines:gasoline"
		value = 600000

	[["Machine Options".combustionFluids]]
		fluid = "assemblylinemachines:diesel"
		value = 1050000

	#What fluids should be valid for use as coolant in Combustion and Geothermal Generators?
	#Value is multiplier on burn time, for example "2" will multiply the total FE by 2.
	[["Machine Options".coolantFluids]]
		fluid = "minecraft:water"
		value = 2

	[["Machine Options".coolantFluids]]
		fluid = "assemblylinemachines:condensed_void"
		value = 4

["Tools and Armor"]
	#What multiplier should each level of the Overclock enchantment give?
	#For example, the default of "0.2" is a 20% increase per enchantment level.
	overclockEnchantmentMultiplier = 0.2

	["Tools and Armor".Titanium]
		#What is the base damage Titanium Tools should do?
		titaniumToolAttack = 5.0
		#What is the base harvest speed Titanium Tools should do?
		titaniumToolHarvestSpeed = 7.0
		#What should the enchantability of Titanium Tools and Armor be?
		titaniumEnchantability = 8
		#What should the base durability of Titanium Tools and Armor be?
		titaniumDurability = 1150
		#What should the knockback resistance of Titanium Armor be?
		titaniumArmorKnockbackResistance = 0.0
		#What should the base damage reduction of Titanium Armor be?
		titaniumArmorDamageReduction = 4
		#What should the toughness of Titanium Armor be?
		titaniumArmorToughness = 0.0

	["Tools and Armor".Steel]
		#What is the base damage Steel Tools should do?
		steelToolAttack = 7.0
		#What is the base harvest speed Steel Tools should do?
		steelToolHarvestSpeed = 9.0
		#What should the enchantability of Steel Tools and Armor be?
		steelEnchantability = 6
		#What should the base durability of Steel Tools and Armor be?
		steelDurability = 1800
		#What should the knockback resistance of Steel Armor be?
		steelArmorKnockbackResistance = 0.1
		#What should the base damage reduction of Steel Armor be?
		steelArmorDamageReduction = 4
		#What should the toughness of Steel Armor be?
		steelArmorToughness = 0.5

	["Tools and Armor".Crank-Powered]
		#What is the base damage Crank-Powered Tools should do?
		crankToolAttack = 8.0
		#What is the base harvest speed Crank-Powered Tools should do?
		crankToolHarvestSpeed = 11.0
		#What should the enchantability of Crank-Powered Tools be?
		crankToolEnchantability = 16
		#What should the base physical durability of Crank-Powered Tools be?
		crankToolDurability = 75
		#What should the base kinetic durability (Cranks) of Crank-Powered Tools be?
		crankToolMaxCranks = 750

	["Tools and Armor".Mystium]
		#What is the base damage Mystium Tools should do?
		mystiumToolAttack = 9.0
		#What is the base harvest speed Mystium Tools should do?
		mystiumToolHarvestSpeed = 19.0
		#What should the enchantability of Mystium Tools be?
		mystiumToolEnchantability = 28
		#What should the base physical durability of Mystium Tools be?
		mystiumToolDurability = 150
		#What should the base electrical durability (Forge Energy) of Mystium Tools be?
		mystiumToolMaxFE = 1000000

	["Tools and Armor".Novasteel]
		#What is the base damage Novasteel Tools should do?
		novasteelToolAttack = 10.5
		#What is the base harvest speed Novasteel Tools should do?
		novasteelToolHarvestSpeed = 23.0
		#What should the enchantability of Novasteel Tools be?
		novasteelToolEnchantability = 37
		#What should the base physical durability of Novasteel Tools be?
		novasteelToolDurability = 300
		#What should the base electrical durability (Forge Energy) of Novasteel Tools be?
		novasteelToolMaxFE = 20000000

[World]
	#Should Mystium Farmland get exhausted over time and stop performing grow operations?
	mystiumFarmlandDeath = true
	#Should the update check message be sent when a player joins a single-player world/the SMP server?
	updateChecker = true
	#Should Gasoline and Diesel explode when placed next to a flammable block?
	gasolineExplosions = true
	#When Patchouli is installed, should players be automatically given the Guidebook when they first connect?
	guideBook = true

	[World."Titanium Generation"]
		#What should the maximum size per vein of Titanium Ore be?
		#Set to 0 to disable Titanium Ore generation.
		titaniumVeinSize = 5
		#How many veins of Titanium Ore should generate per chunk?
		#Set to 0 to disable Titanium Ore generation.
		titaniumFrequency = 7
		#What is the minimum Y value Titanium Ore should spawn at in the overworld?
		#This can (and by default, does) go below the minimum world limit to change the TRIANGLE-style weighting of generation.
		titaniumMinHeight = -112
		#What is the maximum Y value Titanium Ore should spawn at in the overworld?
		titaniumMaxHeight = -16
		#What style of ore generation should Titanium Ore use?
		#TRIANGLE - Most generation occurs in center of min-max range - Akin to Coal Ore at most altitudes.
		#UNIFORM - All generation is equal between min-max range - Akin to Redstone Ore at most altitudes.
		#Allowed Values: UNIFORM, TRIANGLE
		titaniumOreGenStyle = "TRIANGLE"

	[World."Black Granite Generation"]
		#Should generated Black Granite have the "natural" tag?
		#This tag, if present, will only allow Black Granite to be dropped if mined with a Crank-Powered Pickaxe.
		#This is the intended progression, but can be disabled in order to make all Pickaxes mine it.
		blackGraniteSpawnsWithNaturalTag = true
		#What should the maximum size per vein of Black Granite be?
		#Set to 0 to disable Black Granite generation.
		blackGraniteVeinSize = 37
		#How many veins of Black Granite should generate per chunk?
		#Set to 0 to disable Black Granite generation.
		blackGraniteFrequency = 7

	[World."Chromium Generation"]
		#What should the maximum size per vein of Chromium Ore be?
		#Set to 0 to disable Chromium Ore generation.
		chromiumVeinSize = 10
		#How many veins of Chromium Ore should generate per chunk?
		#Set to 0 to disable Chromium Ore generation.
		chromiumFrequency = 4
		#Should Chromium Ore generate on the Dragon Island in The End?
		#If false, Chromium Ore will only generate on the outer End islands accessed by the End Gateway.
		chromiumOnDragonIsland = false

["Client-Side-Only Options"]
	#Do you want to enable "Cool Dude Mode", enabling easter-egg/meme effects?
	#There are no effects on gameplay, except some text, graphics, and names.
	coolDudeMode = false
	#If JEI is installed, should support be enabled?
	jeiSupport = true

