#Enable and disable damage numbers
damage_numbers = true
#Enable this to prevent your equipment from getting damaged when attacking the dummy
disable_equipment_damage = true
#Time in ticks that it takes for a dummy to be considered out of combat after having recieved damage
#Range: 20 ~ 1000
maximum_out_of_combat_interval = 120

[scarecrow]
	#All animal entities will be scared. add here additional ones that are not included
	mobs_whitelist = [""]
	#Animal entities that will not be scared
	mobs_blacklist = [""]
	#Scaring radius
	#Range: 0 ~ 100
	scare_radius = 12

