#All configs are moved to [gameDir]/saves/[save]/serverconfig/fluxnetworks-server.toml
#or [gameDir]/world/serverconfig/fluxnetworks-server.toml
#Copy to [gameDir]/defaultconfig/fluxnetworks-server.toml for modpacks
placeholder = true

