#Stop mods from adding custom flowers
flowers = true
#Stop mods from adding surface structures
surface_structures = true
#Stop mods from adding entities
entities = true
#Stop mods from adding lakes
lakes = true
#Main world id
main_world = "minecraft:overworld"

