#Range: 0.0 ~ 9999.0
chunk_loader_multiplier = 1.0
#How often vitric cactus spawns. A larger number is more rare. Default cactus is 6-13, set to zero to disable.
#Range: 0 ~ 9999
vitric_cactus_rarity = 100
#Requires that vitric cactus be grown only in desert and mesa biomes.
vitric_cactus_desert_only = true
#Sets the max speed of various rail types. Default rails are 0.4.
#Range: 0.1 ~ 10.0
wood_rails_max_speed = 0.2
#Range: 0.1 ~ 10.0
maglev_rails_max_speed = 1.0
#Range: 0.1 ~ 10.0
lightspeed_rails_max_speed = 2.5
#Sets the extra speed boost given by turbo rails. 0.06 is the default for regular powered rails.
#Range: 0.0 ~ 1.0
turbo_rails_boost = 0.2

