
#Planes client settings
[general_client]
	#Third person camera zoom on a plane
	#Range: 1.0 ~ 2.0
	plane_camera_distance_multiplier = 1.0
	#Third person camera zoom on a large plane
	#Range: 1.0 ~ 2.0
	large_plane_camera_distance_multiplier = 1.3
	#Third person camera zoom on a helicopter
	#Range: 1.0 ~ 2.0
	heli_camera_distance_multiplier = 1.2

