
[biome_dictionary]
	#
	# A list of mod IDs that will be ignored when the biome dictionary attempts to register unregistered biomes.
	# Example: ["biomesoplenty", "byg", "autumnity"]
	# Default: []
	ignored_mods = []
	#
	# Determines if the biome dictionary should make assumptions for unregistered biomes. Setting this to false can fix issues where a structure generates weird biomes.
	# Default: true
	make_best_guess = true

[vanilla_enhancements]
	#
	# When true, removes the size limit from the fill and clone commands.
	# Default: true
	exceed_fill_and_clone_limit = true
	#
	# Adds more vanilla structures to the list of structures that lakes cannot generate inside of. Only villages when set to false. Requires reload.
	# Default: true
	extra_lake_proofing = true

[console_debug]
	#
	# When true, allows extra debug logging to be printed to the console.
	# Default: false
	console_debug = false

