
[World]

	[World.Ores]

		[World.Ores."Oil Sand"]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 24
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = 40
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 80

		[World.Ores.Apatite]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 9
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 96

		[World.Ores.Silver]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -60
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 40

		[World.Ores.Lead]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -60
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 40

		[World.Ores.Nickel]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -40
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 120

		[World.Ores.Cinnabar]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 1
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 5
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 48

		[World.Ores.Sulfur]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 7
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 32

		[World.Ores.Tin]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 9
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -20
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 60

		[World.Ores.Niter]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 7
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = 64

