
#
# Average distance between spawn attempts for Repurposed Structures Igloos.
# 1 for spawning in most chunks and 1001 for none.
[Igloos]
	#Range: 1 ~ 1001
	grassyIglooAverageChunkDistance = 28
	#Range: 1 ~ 1001
	stoneIglooAverageChunkDistance = 28
	#Range: 1 ~ 1001
	mushroomIglooAverageChunkDistance = 39

