
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Outposts.
# Will replace Vanilla Outposts with RS's themed Outposts if both would've been in same biome.
# 1 for spawning in most chunks and 1001 for none.
# Note: Vanilla Outposts will spawn again if a RS Outpost's entry is set to 1001 for the biome.
[Outposts]
	#Range: 1 ~ 1001
	outpostBirchAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostJungleAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostGiantTreeTaigaAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostDesertAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostBadlandsAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostSnowyAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostIcyAverageChunkDistance = 41
	#Range: 1 ~ 1001
	outpostOakAverageChunkDistance = 49
	#Range: 1 ~ 1001
	outpostTaigaAverageChunkDistance = 49
	#Range: 1 ~ 1001
	netherBrickOutpostAverageChunkDistance = 34
	#Range: 1 ~ 1001
	warpedOutpostAverageChunkDistance = 34
	#Range: 1 ~ 1001
	crimsonOutpostAverageChunkDistance = 34
	#Range: 1 ~ 1001
	outpostEndAverageChunkDistance = 61

