
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Villages 
# 1 for spawning in most chunks and 1001 for no spawn.
[Spawnrates]
	#Range: 1 ~ 1001
	badlandsVillageAverageChunkDistance = 37
	#Range: 1 ~ 1001
	birchVillageAverageChunkDistance = 52
	#Range: 1 ~ 1001
	darkForestVillageAverageChunkDistance = 47
	#Range: 1 ~ 1001
	jungleVillageAverageChunkDistance = 52
	#Range: 1 ~ 1001
	swampVillageAverageChunkDistance = 52
	#Range: 1 ~ 1001
	mountainsVillageAverageChunkDistance = 52
	#Range: 1 ~ 1001
	villageMushroomAverageChunkDistance = 24
	#Range: 1 ~ 1001
	giantTaigaVillageAverageChunkDistance = 47
	#Range: 1 ~ 1001
	oakVillageAverageChunkDistance = 52
	#Range: 1 ~ 1001
	crimsonVillageAverageChunkDistance = 30
	#Range: 1 ~ 1001
	warpedVillageAverageChunkDistance = 30

#-----------------------------------------------------------------------------------------
# Size of the village. This is how many pieces long a path can be from the start piece.
[Size]
	#Range: 1 ~ 30
	badlandsVillageSize = 10
	#Range: 1 ~ 30
	birchVillageSize = 6
	#Range: 1 ~ 30
	darkForestVillageSize = 6
	#Range: 1 ~ 30
	jungleVillageSize = 8
	#Range: 1 ~ 30
	swampVillageSize = 6
	#Range: 1 ~ 30
	mountainsVillageSize = 6
	#Range: 1 ~ 30
	mushroomVillageSize = 8
	#Range: 1 ~ 30
	giantTaigaVillageSize = 6
	#Range: 1 ~ 30
	oakVillageSize = 6
	#Range: 1 ~ 30
	crimsonVillageSize = 6
	#Range: 1 ~ 30
	warpedVillageSize = 6

